POST https://github.com/login/oauth/access_token 
Content-Type: application/json

{
    "client_id":"fea7053d2c2a62e68910",
    "client_secret":"d434dbdd070a079542dcae3a17db2c9ec5b0dfca",
    "code":"355085133f8a9afce311"
}

###
GET https://api.github.com/search/repositories?q=taykavol/
Authorization: token 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
# Accept: application/vnd.github.v3+json

###
GET https://api.github.com/search/users?q=Tayka
Authorization: token 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
Accept: application/vnd.github.v3+json